#
# install the mysql driver
#   gem install mysql2
#
#
# ensure the mysql gem is defined in your gemfile
#   gem 'mysql2'
#
# and be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#
#  add " gem 'mysql2' " to the gem file

production:
  adapter: mysql2
  database: aurasys
  host: localhost
  username: aurauser
  password: aurauser
  encoding: utf8

development:
  adapter: mysql2
  database: aurasys_development
  host: localhost
  username: aurauser
  password: aurauser
  encoding: utf8

test:
  adapter: mysql2
  database: aurasys_test
  host: localhost
  username: aurauser
  password: aurauser
  encoding: utf8